# action.yaml
name: 'Sarif filter'
description: 'A GitHub Action that filters entries in a sarif file based on teh minimum severity'
inputs:
  input:
    description: 'Input file to filter'
    required: true
  output:
    description: 'Output filtered file'
    required: true
  severity:
    description: 'minimal severity, it can be critical, high, medium or low, anything lower than the chosen will be dropped'
    required: true
    default: "high"
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Filter
      id: filter
      shell: bash
      run: python sarif-filter.py --min-severity ${{ inputs.severity }} ${{ inputs.input }} ${{ inputs.output }}  
